Refinements
Michi-App/michi pull request #2
Opened 2024-03-10 10:27 UTC by bebop23

-  [improve setup instructions and create-wallet signature rejection](https://github.com/Michi-App/michi/commit/d8fd09c8537ddd787ff0ad799a5eb5d3977dcf12)
- [refresh data correctly when deposits or withdrawals are made](https://github.com/Michi-App/michi/commit/f2a43c707b2d554de72e0ef65dc38c093cc042a6)
- [correctly detect when a new chest is created and refresh the data](https://github.com/Michi-App/michi/commit/701dc6fc3caf5d84c5f1f177b3482284c52bd66d)

2024-03-10 15:01 UTC, glebshkut requested changes
Really good stuff, I love it. But noticed a few small things

2024-03-10 15:01 UTC, glebshkut commented on frontend/src/features/WalletView.tsx
> +    if (isWithdrawalConfirming) {
shouldn't `isWithdrawalConfirmed` be here?

2024-03-10 15:01 UTC, glebshkut commented on frontend/src/features/CreateNewWallet.tsx
>    const [isButtonLoading, setIsButtonLoading] = useState(false);
it's unused, can be deleted

2024-03-10 17:41 UTC, bebop23 commented on frontend/src/features/WalletView.tsx
> +    if (isWithdrawalConfirming) {
yea, good catch

2024-03-10 18:01 UTC, glebshkut reviewed
Withdrawal still doesn't have a loading spinner, other than that LGTM

2024-03-10 18:01 UTC, glebshkut commented on frontend/src/features/WalletView.tsx
> +          {isPending || isConfirming &&
Consider adding `isProcessing` here, cause there's no loading spinner appearing while withdrawing

2024-03-11 04:15 UTC, bebop23 commented on frontend/src/features/WalletView.tsx
> +          {isPending || isConfirming &&
added

2024-03-11 04:55 UTC, glebshkut approved these changes

2024-03-11 05:16 UTC, merged